config/routes.rb
Rails.application.routes.draw do
  resources :events, only: %i[new create show index]
  resources :users, only: %i[new create show]
  root 'events#index'
  get 'attendances/create'
  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in_new'
  get '/sign_out', to: 'users#sign_out'
  post '/sign_in', to: 'events#enroll'
  resources :attendances
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :attendances
  has_many :attendee, through: :attendances, source: :user

  validates :name, presence: true
  validates :description, presence: true
  validates :date, presence: true

  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :past, -> { where('date < ? ', DateTime.now) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, class_name: 'Event'
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  scope :upcoming, -> { where('date >= ?', Date.today) }
  scope :past, -> { where('date < ? ', Date.today) }
end

app/controllers/application_controller.rb
require 'date'
class ApplicationController < ActionController::Base
  def date_now
    date = DateTime.now
    date.localtime.strftime('%m/%d/%Y %H:%M')
  end
  helper_method :current_user_now
  def current_user_now
    User.find(session[:current_user]['id'])
  end
end

app/controllers/attendances_controller.rb
# rubocop:disable Layout/LineLength

class AttendancesController < ApplicationController
  def create
    if User.find(params[:user][:user_id]).attendances.where(event_id: params[:event_id]).none?
      user = User.find(params[:user][:user_id])
      a = Attendance.new(event_id: params[:event_id], user_id: user.id)
      a.save
      msg = build_msg
    else
      msg = "You are already attending to #{Event.find(params[:event_id]).name}"
    end
    redirect_to event_path(params[:event_id]), notice: msg
  end

  private

  def build_msg
    if (params[:user][:user_id]).to_i == session[:current_user]['id']
      msg = "You decided to attend #{Event.find(params[:event_id]).name}"
    else
      msg = "You decided to invite #{User.find(params[:user][:user_id]).username} to attend #{Event.find(params[:event_id]).name}"
    end
    msg
  end
end

# rubocop:enable Layout/LineLength

app/controllers/atttendances_controller.rb
# rubocop:disable Layout/LineLength

class AttendancesController < ApplicationController
  def create
    if User.find(params[:user][:user_id]).attendances.where(event_id: params[:event_id]).none?
      user = User.find(params[:user][:user_id])
      a = Attendance.new(event_id: params[:event_id], user_id: user.id)
      a.save
      msg = build_msg
    else
      msg = "You are already attending to #{Event.find(params[:event_id]).name}"
    end
    redirect_to event_path(params[:event_id]), notice: msg
  end

  private

  def build_msg
    if (params[:user][:user_id]).to_i == session[:current_user]['id']
      msg = "You decided to attend #{Event.find(params[:event_id]).name}"
    else
      msg = "You decided to invite #{User.find(params[:user][:user_id]).username} to attend #{Event.find(params[:event_id]).name}"
    end
    msg
  end
end

# rubocop:enable Layout/LineLength

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  include UsersHelper

  def index
    @upcoming = Event.upcoming.sort { |a, b| a.date <=> b.date }
    @past = Event.past.sort { |a, b| b.date <=> a.date }
  end

  def show
    if session[:current_user]
      @event = Event.find(params[:id])
      @date = date_now
      @attendance = Attendance.new
      @users_not_in = User.all.where.not(id: @event.attendee).where.not(id: session[:current_user]['id'])
    else
      redirect_to sign_in_path
    end
  end

  def create
    user = User.find(session[:current_user]['id'])
    @event = user.events.build(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def new
    if session[:current_user]
      @event = Event.new
    else
      redirect_to sign_in_path
    end
  end

  def enroll
    @user = User.find_by(username: params[:username])
    current_user(@user.id) if @user && params[:password] == @user.password
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
require 'date'

class UsersController < ApplicationController
  include UsersHelper

  def new
    if session[:current_user]
      redirect_to events_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      current_user(@user.id)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    if session[:current_user]
      @user = User.find(params[:id])
      current_user(@user.id)
      @date = date_now
      @attended_events = @user.attended_events.sort { |a, b| b.date <=> a.date }
      @upcoming = @user.attended_events.upcoming
      @past = @user.attended_events.past
      @my_events = @user.events
    else
      redirect_to sign_in_path
    end
  end

  def sign_in_new
    @user = User.find_by(username: params[:username])
    if @user && params[:password] == @user.password
      current_user(@user.id)
      redirect_to root_path
    else
      redirect_to sign_in_path, notice: 'User or password wrong'
    end
  end

  def sign_in
    redirect_to events_path if session[:current_user]
  end

  def sign_out
    reset_session
    redirect_to sign_in_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?
    session[:current_user] = User.find(params[:id])
    session[:current_user]
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:name, :description, :date, :creator_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user(id)
    session[:current_user] = User.find(id)
    session[:current_user]
  end

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/views/events/_feed.html.erb
<div class="column is-mobile is-half">
  <p class="control is-1 mb-2">
    <%= link_to 'Upcoming Events', events_path, class: "button is-danger is-outlined" %>
  </p>
  <% @upcoming.each do | event | %>
    <div class="box">
      <article class="media">
          <div class="media-left">
            <figure class="image is-64x64">
              <%= gravatar_image_tag(event.creator.email, size: 64, alt: event.creator.username) %>
            </figure>
          </div>
          <div class="media-content">
            <div class="content">     
              <strong><%= link_to event.name, event_path(event.id) %></strong><br />
              <small><%= event.creator.username %></small><br/>         
              <p><%= event.description %></p>
              <small><%= content_tag(:p, "#{event.date.localtime.strftime("%a, %b %d, %Y")}  -  #{event.date.localtime.strftime("%I:%M %P")}", class: "date-time") %></small>
            </div>
          </div>
      </article>
    </div>
  <% end %>
</div>
<div class="column is-mobile is-half">
  <p class="control is-1 mb-2">
    <%= link_to 'Past Events', events_path, class: "button is-danger is-outlined" %>
  </p>
  <% @past.each do | event | %>
    <div class="box">
      <article class="media">
          <div class="media-left">
            <figure class="image is-64x64">
              <%= gravatar_image_tag(event.creator.email, size: 64, alt: event.creator.username) %>
            </figure>
          </div>
          <div class="media-content">
            <div class="content">     
              <strong><%= link_to event.name, event_path(event.id) %></strong><br />
              <small><%= event.creator.username %></small><br/>         
              <p><%= event.description %></p>
              <small><%= content_tag(:p, "#{event.date.localtime.strftime("%a, %b %d, %Y")}  -  #{event.date.localtime.strftime("%I:%M %P")}", class: "date-time") %></small>
            </div>
          </div>
      </article>
    </div>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :name, label: "What's the name of your event?", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "My event is...", autofocus: true %>
      <%= f.input :description, label: "Describe your event", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "My event is about... and will be in this location...", autofocus: false %>
      <%= f.input :date, label: "When will be?", input_html: { class: "datetime"}, wrapper: false, label_html: {class: "label"}%>
    </div>
  </div>
  <%= f.button :submit, class: "button is-danger is-light" %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-mobile">
       <%= render 'feed' %>
    </div>
    <p class="columns is-mobile is-centered">
      <%= link_to 'Click here if you want to create a new event', new_event_path, class: "button is-danger is-light" %>
    </p>
  </div>
  
</section>

app/views/events/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a New Event</h1>
					<%= render 'form', event: @event %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', events_path, class: "button is-danger" %>
				</p>
		</div>
	</div>
</nav>

app/views/events/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <h5 class="title is-size-1">
        <%= @event.name %>
      </h5>
    </div>
    <p class="columns is-centered mt-5 is-size-3">
      <%= @event.description %>
    </p>
    <p class="columns is-justify-content-flex-end mt-3 is-size-5">
      <%= @event.date.localtime.strftime("%a, %b %d, %Y") %>
      <%= @event.date.localtime.strftime("%I:%M %P")%>
    </p>
    <span class="is-justify-content-flex-start">
      <% if @event.date.localtime.strftime("%m/%d/%Y %H:%M") > @date %>
        <% if session[:current_user] && !current_user_now.attended_events.where(id: @event.id).any? %>
          <%= simple_form_for(@attendance) do |f| %>
            <%= hidden_field_tag :event_id, @event.id %>
      <%=hidden_field_tag :user_id, session[:current_user]['id'], {id: 'user_user_id', name: 'user[user_id]'}%>
            <%= f.button :submit, class: "button is-danger" %>
          <% end %>
        <% end %>
      <% end %>
    </span>  
    <% if @event.attendee.any? %>
      <h4 class="columns subtitle is-centered">
        Attendees
      </h4>
      <div class="content columns is-centered">
        <ol type="1">
          <% @event.attendee.each do |attendee| %>
            <li>
              <%= attendee.username %>
            </li>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
  		<div class="notification is-danger is-light">
        <button class="delete"></button>
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
        <button class="delete"></button>
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
    <nav class="navbar is-light">
  		<div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4 ml-5">Private Events</h1>
        <% end %>
  	 </div>
     <div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					<div class="field is-grouped is-mobile">
						
            <% if session[:current_user] %>
              <p class="control">
							<%= link_to 'All Events', root_path, class: "button is-danger is-rounded is-outlined" %>
						  </p>
              <p class="control">
							<%= link_to 'New Event', new_event_path, class: "button is-danger is-rounded" %>
						  </p>
              <p class="control">
                <%= link_to "My Events", user_path(session[:current_user]['id']), class: "button is-danger is-inverted" %>
              </p>
              <p>
                <%= link_to "Logout", sign_out_path, class:"button is-danger is-inverted" %>
              </p>
            <% else %>
            <p class="control">
							<%= link_to 'All Events', root_path, class: "button is-danger is-rounded is-outlined" %>
						</p>
            <p class="control">
              <%= link_to 'Sign In', sign_in_path, class: "button is-danger is-inverted" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_path, class: "button is-danger is-inverted" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
    </nav>
    <%= yield %>
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', () => {
        (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
          const $notification = $delete.parentNode;

          $delete.addEventListener('click', () => {
            $notification.parentNode.removeChild($notification);
          });
        });
      });
    </script>
  </body>
</html>

app/views/users/new.html.erb
<div class="section">
	<div class="container box">
	<div class="columns is-centered">

		<div class="column is-4">
			
		<h2 class="title is-1 sign-new">Sign Up</h2>

		<%= simple_form_for @user do |f| %>
	  <%= f.error_notification %>


		<div class="field">
	  	<div class="control">
	    <%= f.input :username, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
	  	</div>
		</div>

		<div class="field">
	  	<div class="control">
	    <%= f.input :email, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
	  	</div>
		</div>
  
		  
		<div class="field">
			<div class="control">
				<%= f.input :password, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" }, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
			</div>
		</div>

		<div class="field">
			<div class="control">
		 		<%= f.button :submit, "Sign up", class:"button button is-danger is-light" %>
		 	</div>
		</div>

		<% end %>
			<br />
		</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <p class="has-text-centered is-size-1 has-text-weight-bold mb-5">All My Events</p>
  <div class="columns">
    <div class="column is-mobile is-half">
      <p class="title has-text-primary-dark has-text-centered">Upcoming Events</p>
      <% if @upcoming.any? %>
        <div class="upcoming-list">
          <ul>
            <% @attended_events.each do |event| %>
              <% if event.date.localtime.strftime("%m/%d/%Y %H:%M") > @date %>
              <li class="box">
                <%= link_to  event.name , event_path(event.id) %>
                <%= content_tag(:p, "#{event.date.localtime.strftime("%a, %b %d, %Y")}  -  #{event.date.localtime.strftime("%I:%M %P")}", class: "date-time") %>
              </li>
              <% end %>
            <% end %>
          </ul>
       </div>
      <% end %>
    </div>
    <div class= "column">
      <p class="title has-text-danger-dark has-text-centered">Past Events</p>
      <% if @past.any? %>
        <div class="past-cont">
          <ul class="events">
            <% @attended_events.each do |event| %>
              <% if event.date.localtime.strftime("%m/%d/%Y %H:%M") < @date %>
                <li class="box">
                  <%= link_to  event.name , event_path(event.id) %>
                  <%= content_tag(:p, "#{event.date.localtime.strftime("%a, %b %d, %Y")}  -  #{event.date.localtime.strftime("%I:%M %P")}", class: "date-time") %>
                </li>
              <% end %>
            <%end%>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <div class="columns">
    <% if @my_events.any? %>
      <div class="column">
        <p class="title has-text-dark has-text-centered">Created Events</p>
        <ul class="created-events-list">
          <% @my_events.each do |event| %>
            <li class="box has-text-centered">
              <%= link_to  event.name, event_path(event.id) %>
              <%= content_tag(:p, "#{event.date.localtime.strftime("%a, %b %d, %Y")}  -  #{event.date.localtime.strftime("%I:%M %P")}", class: "date-time") %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/users/sign_in.html.erb
<section class="section">
	<div class="container">
		<div class="columns is-centered box">
			<div class="column is-4">
				<h2 class="title is-1 log-new">Log in</h2>
				<%= form_with model: @user, class: "login-form" do |f| %>

				  <div class="field">
				  	<div class="control">
				    	<%= f.label :username, class: "label" %>
              <%= f.text_field :username, class: "input is-small" %>
				    </div>
				  </div>

				  <div class="field">
				  	<div class="control">
            <%= f.label :password, class: "label" %>
            <%= f.password_field :password, class: "input is-small" %>
						</div>
					</div>

				  <%= f.submit "Log in", class:"button is-danger is-light is-medium" %>
				<% end %>
				<br/>
        <div class="is-size-9">
          <%= link_to  "Sign up", new_user_path %>
        </div>
        <p class="flash"><%=flash.notice%></p>
			</div>
		</div>
	</div>
</section>